# Generated by Django 5.1.7 on 2025-04-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
