# Generated by Django 5.1.7 on 2025-04-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_mesa_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.IntegerField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mesero',
            name='telefono',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
